Fix Date() to get user Local date, and fix Bug in EditVC when item is…
dannysanchez559/Grocery-List pull request #6
Opened 2020-12-18 04:10 UTC by dannysanchez559

Needs additional testing for bugs when creating new items, and when items go past exp date, and exp are updated.

2020-12-18 08:40 UTC, amerikan requested changes

2020-12-18 08:40 UTC, amerikan commented on Grocery List/Controllers/EditItemViewController.swift
> +        stepperButton.value = daysTillExpired == 0 ? 0 : Double(daysTillExpired)
Nice! You can technically also add parentheses around the condition to make it easier to read i.e.
```swift
stepperButton.value = (daysTillExpired == 0) ? 0 : Double(daysTillExpired)
```

2020-12-18 08:40 UTC, amerikan commented on Grocery List/Controllers/EditItemViewController.swift
> +//        print("daysTillExpInStepper: \(daysTillExpired)")
Unless you're going to use this commented code very soon, I'd remove it. Otherwise these comments will start accumulating as time passes.

2020-12-18 08:40 UTC, amerikan commented on Grocery List/Controllers/EditItemViewController.swift
> +        //print("secondsTowholeDays: \(secondsToWholeDays)")
Remove commented code unless you're going to be using it soon.

2020-12-18 08:45 UTC, amerikan commented
Interesting choice for branch name, I almost thought it was actually a zero-day vulnerability! 🤣 https://en.wikipedia.org/wiki/Zero-day_(computing)

2020-12-20 22:23 UTC, amerikan requested changes

2020-12-20 22:23 UTC, amerikan commented on .gitignore
> +xcworkspace/
Why don't you want to track xcworkspace? Isn't it important to have in repo?

2020-12-21 00:10 UTC, dannysanchez559 commented
I don’t remember it being pushed to gh before.

I think its just the current screen you’ve last worked on when in xcode.
Have you tried without it?

On Sun, Dec 20, 2020 at 2:23 PM Erik Montes <notifications@github.com>
wrote:

> *@amerikan* requested changes on this pull request.
> ------------------------------
>
> In .gitignore
> <https://github.com/dannysanchez559/Grocery-List/pull/6#discussion_r546444554>
> :
>
> > @@ -4,6 +4,7 @@
>
>  ## User settings
>  xcuserdata/
> +xcworkspace/
>
> Why don't you want to track xcworkspace? Isn't it important to have in
> repo?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dannysanchez559/Grocery-List/pull/6#pullrequestreview-556066854>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF375OQRR3WCJQQJKF6ZFF3SVZ2OVANCNFSM4VAT6OGQ>
> .
>

2020-12-21 02:08 UTC, dannysanchez559 commented on Grocery List/Controllers/EditItemViewController.swift
> +//        print("daysTillExpInStepper: \(daysTillExpired)")
yep still needs additional testing

2020-12-21 02:11 UTC, dannysanchez559 commented on .gitignore
> +xcworkspace/
Everytime i move around in Xcode, this xcworkspace gets marked as changed. Even though i have not made any changes to project or added any code. 
I think this is just a marker to tell xcode what screen the user last left on. Dont believe it's required for repo.

2020-12-21 06:40 UTC, merged